# Generated by Django 5.2.6 on 2025-09-05 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('letra', models.TextField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField()),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='artista.artista')),
            ],
        ),
    ]
